#! /usr/bin/env python3

import click
import os
from ensembldb.core import init


@click.group()
def cli():
    pass


@cli.command('init')
@click.option(
    '--db_path',
    type=click.Path(),
    required=True,
    help='Ensembl database local path.')
def init_db():
    click.secho('init database')
    if 'ENSEMBL_DB_PATH' not in os.environ:
        init.setup_db_env()


@cli.command('show')
def show_db():
    click.secho('show database')


if __name__ == '__main__':
    cli()
