#! /usr/bin/env python3

import click
import os
from ensembldb.core import init


@click.group()
def cli():
    pass


@cli.command('init')
@click.option(
    '--db_path',
    type=click.Path(),
    required=True,
    help='Ensembl database local path.')
def init_db(db_path):
    click.secho('#init database')
    click.secho('#check ensembldb database...')
    init.setup_db_sqlit(db_path)
    click.secho('#check environment variable...')
    init.setup_db_env(db_path)


@cli.command('show')
def show_db():
    click.secho('show database')


if __name__ == '__main__':
    cli()
